spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d9c739e17449e17b9470514b27f11ceb
            client-secret: "" # 필요없으면 비워둠
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/callback
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

